import { Injectable, signal } from '@angular/core';

export type SupportedLanguage = 'en' | 'ar';

const translations: Record<string, string> = {
  'Workforce360': 'القوى العاملة 360',
  'HR Workspace': 'مساحة الموارد البشرية',
  'Main navigation': 'التنقل الرئيسي',
  'Dashboard': 'لوحة التحكم',
  'Employees': 'الموظفون',
  'Attendance': 'الحضور',
  'Reports': 'التقارير',
  'Settings': 'الإعدادات',
  'English': 'الإنجليزية',
  'Arabic': 'العربية',
  'Switch to English': 'التبديل إلى الإنجليزية',
  'Switch to Arabic': 'التبديل إلى العربية',
  'Search employees...': 'البحث عن الموظفين...',
  'Manage your organization\'s employees': 'إدارة موظفي مؤسستك',
  'Add Employee': 'إضافة موظف',
  'Search employees': 'البحث عن الموظفين',
  'Department': 'القسم',
  'All Departments': 'جميع الأقسام',
  'Human Resources': 'الموارد البشرية',
  'Engineering': 'الهندسة',
  'Finance': 'المالية',
  'Marketing': 'التسويق',
  'Status': 'الحالة',
  'All Status': 'جميع الحالات',
  'Active': 'نشط',
  'Employee': 'الموظف',
  'Position': 'المسمى الوظيفي',
  'Join Date': 'تاريخ الانضمام',
  'Actions': 'الإجراءات',
  'No employees found': 'لم يتم العثور على موظفين',
  'Try changing your search or filters.': 'جرّب تغيير البحث أو عوامل التصفية.',
  'Departments': 'الأقسام',
  'Manage your organization\'s departments and teams.': 'إدارة أقسام وفرق مؤسستك.',
  'Add Department': 'إضافة قسم',
  'Total Departments': 'إجمالي الأقسام',
  'Active Departments': 'الأقسام النشطة',
  'Search departments...': 'البحث عن الأقسام...',
  'Describe the department...': 'صف القسم...',
  'Enter manager name': 'أدخل اسم المدير',
  'e.g. Information Technology': 'مثال: تقنية المعلومات',
  'Inactive': 'غير نشط',
  'Manager': 'المدير',
  'No departments found': 'لم يتم العثور على أقسام',
  'Try changing your search or filter.': 'جرّب تغيير البحث أو عامل التصفية.',
  'Edit Department': 'تعديل القسم',
  'Update department information.': 'تحديث معلومات القسم.',
  'Create a new department.': 'إنشاء قسم جديد.',
  'Department Name': 'اسم القسم',
  'Description': 'الوصف',
  'Department Manager': 'مدير القسم',
  'Cancel': 'إلغاء',
  'Save Changes': 'حفظ التغييرات',
  'Add Attendance': 'إضافة سجل حضور',
  'Total Records': 'إجمالي السجلات',
  'Present Today': 'الحاضرون اليوم',
  'Absent Today': 'الغائبون اليوم',
  'On Leave': 'في إجازة',
  'Search attendance records...': 'البحث في سجلات الحضور...',
  'Track employee attendance and daily working hours.': 'متابعة حضور الموظفين وساعات العمل اليومية.',
  'Present': 'حاضر',
  'Absent': 'غائب',
  'Date': 'التاريخ',
  'Check In': 'تسجيل الحضور',
  'Check Out': 'تسجيل الانصراف',
  'Clear Filters': 'مسح عوامل التصفية',
  'Edit Attendance': 'تعديل سجل الحضور',
  'Update attendance information.': 'تحديث معلومات الحضور.',
  'Add a daily attendance record.': 'إضافة سجل حضور يومي.',
  'Employee Name': 'اسم الموظف',
  'Employee ID': 'الرقم الوظيفي',
  'Save Profile': 'حفظ الملف الشخصي',
  'Save Preferences': 'حفظ التفضيلات',
  'Save Notifications': 'حفظ الإشعارات',
  'Manage your account, preferences and application settings.': 'إدارة حسابك وتفضيلاتك وإعدادات التطبيق.',
  'Profile': 'الملف الشخصي',
  'General': 'عام',
  'Notifications': 'الإشعارات',
  'Appearance': 'المظهر',
  'Security': 'الأمان',
  'Account': 'الحساب',
  'Profile Information': 'معلومات الملف الشخصي',
  'Manage your personal and professional information.': 'إدارة معلوماتك الشخصية والمهنية.',
  'Full Name': 'الاسم الكامل',
  'Job Title': 'المسمى الوظيفي',
  'Email Address': 'البريد الإلكتروني',
  'Phone Number': 'رقم الهاتف',
  'General Settings': 'الإعدادات العامة',
  'Configure your language, timezone and date preferences.': 'تكوين اللغة والمنطقة الزمنية وتفضيلات التاريخ.',
  'Language': 'اللغة',
  'Timezone': 'المنطقة الزمنية',
  'Date Format': 'تنسيق التاريخ',
  'Choose which notifications you want to receive.': 'اختر الإشعارات التي ترغب في تلقيها.',
  'Email Notifications': 'إشعارات البريد الإلكتروني',
  'Receive important system updates by email.': 'تلقي تحديثات النظام المهمة عبر البريد الإلكتروني.',
  'Attendance Notifications': 'إشعارات الحضور',
  'Get notified about attendance changes.': 'تلقي إشعارات حول تغييرات الحضور.',
  'Employee Notifications': 'إشعارات الموظفين',
  'Receive updates about employee activity.': 'تلقي تحديثات حول أنشطة الموظفين.',
  'Weekly Reports': 'التقارير الأسبوعية',
  'Receive a weekly HR summary report.': 'تلقي تقرير أسبوعي موجز للموارد البشرية.',
  'Customize how Workforce360 looks.': 'تخصيص مظهر Workforce360.',
  'Dark Mode': 'الوضع الداكن',
  'Light Mode': 'الوضع الفاتح',
  'Use a darker interface.': 'استخدام واجهة داكنة.',
  'Use the standard light interface.': 'استخدام الواجهة الفاتحة القياسية.',
  'Manage your account security.': 'إدارة أمان حسابك.',
  'Password': 'كلمة المرور',
  'Keep your password secure and up to date.': 'حافظ على أمان كلمة المرور وحدّثها باستمرار.',
  'Change Password': 'تغيير كلمة المرور',
  'Two-Factor Authentication': 'المصادقة الثنائية',
  'Add an additional layer of security.': 'إضافة طبقة أمان إضافية.',
  'Enabled': 'مفعّل',
  'Disabled': 'معطّل',
  'Enable': 'تفعيل',
  'Disable': 'تعطيل',
  'View your account and login information.': 'عرض معلومات الحساب وتسجيل الدخول.',
  'Account Name': 'اسم الحساب',
  'Role': 'الدور',
  'Last Login': 'آخر تسجيل دخول',
  'Sign Out': 'تسجيل الخروج',
  'Good Morning, Bushra 👋': 'صباح الخير، بشرى 👋',
  'Here\'s what\'s happening with your team today.': 'إليك آخر مستجدات فريقك اليوم.',
  'Total Employees': 'إجمالي الموظفين',
  '↑ 12% from last month': '↑ ١٢٪ مقارنة بالشهر الماضي',
  '87% attendance': 'حضور بنسبة ٨٧٪',
  '7% of total': '٧٪ من الإجمالي',
  'New Joiners': 'الموظفون الجدد',
  'This month': 'هذا الشهر',
  'Jan': 'يناير',
  'Feb': 'فبراير',
  'Mar': 'مارس',
  'Apr': 'أبريل',
  'May': 'مايو',
  'Jun': 'يونيو',
  'Jul': 'يوليو',
  'Aug': 'أغسطس',
  'Sep': 'سبتمبر',
  'Oct': 'أكتوبر',
  'Nov': 'نوفمبر',
  'Dec': 'ديسمبر',
  'Employee Growth': 'نمو الموظفين',
  'Monthly overview': 'نظرة عامة شهرية',
  'Department Overview': 'نظرة عامة على الأقسام',
  'Employees by department': 'الموظفون حسب القسم',
  'Total': 'الإجمالي',
  'Information Technology': 'تقنية المعلومات',
  'Technology, software and infrastructure': 'التقنية والبرمجيات والبنية التحتية',
  'Employee relations and recruitment': 'علاقات الموظفين والتوظيف',
  'Financial planning and accounting': 'التخطيط المالي والمحاسبة',
  'Marketing and communications': 'التسويق والاتصالات',
  'Business operations and administration': 'عمليات الأعمال والإدارة',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Save': 'حفظ',
  'Loading employee...': 'جارٍ تحميل بيانات الموظف...',
  'Employee Details': 'تفاصيل الموظف',
  'View employee information': 'عرض معلومات الموظف',
  'Update employee information': 'تحديث معلومات الموظف',
  'Add a new employee to your organization': 'إضافة موظف جديد إلى مؤسستك',
  'No attendance records found': 'لم يتم العثور على سجلات حضور',
  'Attendance Overview': 'نظرة عامة على الحضور',
  'Attendance distribution for selected period.': 'توزيع الحضور للفترة المحددة.',
  'Attendance Statistics': 'إحصائيات الحضور',
  'Department Statistics': 'إحصائيات الأقسام',
  'Employees by department.': 'الموظفون حسب القسم.',
  'Attendance Performance': 'أداء الحضور',
  'Current attendance breakdown.': 'تفاصيل الحضور الحالية.',
  'Employee Attendance Report': 'تقرير حضور الموظفين',
  'Individual employee attendance statistics.': 'إحصائيات حضور كل موظف.',
  'No employee records found.': 'لم يتم العثور على سجلات موظفين.',
  'Analyze employee, department and attendance performance.': 'تحليل أداء الموظفين والأقسام والحضور.',
  'Print': 'طباعة',
  'Export CSV': 'تصدير CSV',
  'Start Date': 'تاريخ البداية',
  'End Date': 'تاريخ النهاية',
  'Apply Filters': 'تطبيق عوامل التصفية',
  'Active employees': 'الموظفون النشطون',
  'Attendance records': 'سجلات الحضور',
  'Leave records': 'سجلات الإجازات',
  'Attendance Rate': 'معدل الحضور',
  'Overall performance': 'الأداء العام',
  'Leave': 'إجازة',
  'Sales': 'المبيعات',
  'Operations': 'العمليات',
  'IT': 'تقنية المعلومات',
  'HR': 'الموارد البشرية',
  'Change language': 'تغيير اللغة',
  'Are you sure you want to delete': 'هل أنت متأكد أنك تريد حذف',
  'Are you sure you want to sign out?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'You have been signed out.': 'تم تسجيل خروجك.',
  'Unable to load employees. Please try again.': 'تعذر تحميل الموظفين. يرجى المحاولة مرة أخرى.',
  'Unable to delete employee.': 'تعذر حذف الموظف.',
  'Not assigned': 'غير محدد',
  'Edit Employee': 'تعديل الموظف',
  'Personal Information': 'المعلومات الشخصية',
  'Work Information': 'معلومات العمل',
  'First Name': 'الاسم الأول',
  'Last Name': 'اسم العائلة',
  'Phone': 'الهاتف',
  'Save Employee': 'حفظ الموظف',
  'Update Employee': 'تحديث الموظف',
  'Joined': 'تاريخ الانضمام',
  'Employee Overview': 'نظرة عامة على الموظف',
  'Frontend Developer': 'مطور واجهات أمامية',
  'Administrator': 'مدير النظام',
  'HR Administrator': 'مسؤول الموارد البشرية',
  'Today, 09:42 AM': 'اليوم، 09:42 صباحًا',
  'Email': 'البريد الإلكتروني',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<SupportedLanguage>(this.readSavedLanguage());
  readonly isArabic = signal(this.language() === 'ar');

  constructor() {
    this.applyDocumentLanguage();
  }

  toggleLanguage(): void {
    this.setLanguage(this.isArabic() ? 'en' : 'ar');
  }

  setLanguage(language: SupportedLanguage): void {
    this.language.set(language);
    this.isArabic.set(language === 'ar');
    localStorage.setItem('workforce360_language', language);
    this.applyDocumentLanguage();
  }

  translate(value: string): string {
    return this.isArabic() ? (translations[value] ?? value) : value;
  }

  private readSavedLanguage(): SupportedLanguage {
    return localStorage.getItem('workforce360_language') === 'ar' ? 'ar' : 'en';
  }

  private applyDocumentLanguage(): void {
    const language = this.language();
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }
}
